alias h='history 25'
alias j='jobs -l'
alias ls='ls -GF'
alias la='ls -a'
alias lf='ls -FA'
alias ll='ls -lA'
alias rm='rm -iv'
alias cp='cp -ipv'
alias mv='mv -iv'
alias diff='diff -u'
alias ec='env LC_ALL=C LANG=C'
alias tzjp='env TZ=Asia/Tokyo'
alias listpatch='find . -name \*.patch \| cut -c3-'
alias vi='vim'
alias makeclean='make -f ~/.make.conf clean'
alias solve="vim -p '+/[<=>]\{7,\}' \`git status | grep both | cut -f2 -d: | xargs\`"
